"""CSV ingestion for the finance engine (Role 1) -- subscription-billing
schema.

The real dataset (data/subscription_accounts.csv, generated by
data/generate_subscription_data.py) matches the exact column set of
whyledger_frontend_reference_full.csv: one row per customer account per
active calendar month, with MRR lifecycle events (new business, expansion,
contraction, churn, SLA credits, refunds, usage overage), product/support
telemetry, and precomputed variance/driver/historical fields.

This replaces the earlier general-ledger ingestion (account/period/amount
CSVs) -- see git history if that shape is ever needed again. The contract
objects it feeds (Variance/Driver/Transaction in backend/contracts/schemas)
are unchanged, so Role 2's agent_engine and memory needed zero changes.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path

import pandas as pd

REQUIRED_COLUMNS = {
    "account_id", "month", "company_size", "industry", "contract_type",
    "current_mrr", "previous_mrr", "mrr_change", "mrr_change_pct",
    "transaction_ids", "transaction_timestamps", "transaction_types",
    "transaction_amounts", "reason_codes",
    "new_arr_amount", "expansion_amount", "contraction_amount", "churn_amount",
    "sla_credit_amount", "refund_amount", "usage_overage_amount",
    "churn_flag",
}

# The raw schema has no calendar column -- "month" is a global integer index
# shared across every account (see generate_subscription_data.py). This
# anchor must match the generator's BASE_YEAR/BASE_MONTH so period labels
# ("2025-01", ...) stay meaningful and lexicographically sortable (memory's
# get_previous_context relies on that ordering).
BASE_YEAR, BASE_MONTH = 2025, 1

SEGMENT_DIMENSIONS = ["company_size", "industry", "contract_type"]
BILLING_CATEGORIES = [
    "new_arr_amount", "expansion_amount", "contraction_amount", "churn_amount",
    "sla_credit_amount", "refund_amount", "usage_overage_amount",
]

_LIST_COLUMNS = [
    "transaction_ids", "transaction_timestamps", "transaction_types",
    "transaction_amounts", "reason_codes",
]


class DatasetValidationError(ValueError):
    pass


def month_to_period(month_index: int) -> str:
    total = (BASE_MONTH - 1) + (int(month_index) - 1)
    year = BASE_YEAR + total // 12
    month = total % 12 + 1
    return f"{year:04d}-{month:02d}"


def period_to_month(period: str) -> int:
    year, month = (int(x) for x in period.split("-"))
    return (year - BASE_YEAR) * 12 + (month - BASE_MONTH) + 1


def _parse_list_cell(value) -> list:
    if pd.isna(value) or value == "" or value == "[]":
        return []
    return json.loads(value)


@dataclass
class SubscriptionDataset:
    accounts_df: pd.DataFrame
    periods: list[str] = field(default_factory=list)
    account_ids: list[str] = field(default_factory=list)
    company_sizes: list[str] = field(default_factory=list)
    industries: list[str] = field(default_factory=list)
    contract_types: list[str] = field(default_factory=list)

    def info(self) -> dict:
        return {
            "periods": self.periods,
            "transaction_count": int(self.accounts_df["transaction_count"].sum()),
            "account_count": len(self.account_ids),
            "available_dimensions": ["account"] + SEGMENT_DIMENSIONS,
            "billing_categories": [c.replace("_amount", "") for c in BILLING_CATEGORIES],
        }


def _validate_columns(df: pd.DataFrame) -> None:
    missing = REQUIRED_COLUMNS - set(df.columns)
    if missing:
        raise DatasetValidationError(f"Subscription CSV is missing required column(s): {sorted(missing)}")


def load_dataset(path: str | Path) -> SubscriptionDataset:
    df = pd.read_csv(path)
    _validate_columns(df)

    for col in _LIST_COLUMNS:
        df[col] = df[col].apply(_parse_list_cell)

    df["account_id"] = df["account_id"].astype(str)
    df["month"] = df["month"].astype(int)
    df["period"] = df["month"].apply(month_to_period)
    df["churn_flag"] = df["churn_flag"].astype(bool)

    periods = sorted(df["period"].unique())
    account_ids = sorted(df["account_id"].unique())

    return SubscriptionDataset(
        accounts_df=df,
        periods=periods,
        account_ids=account_ids,
        company_sizes=sorted(df["company_size"].dropna().unique()),
        industries=sorted(df["industry"].dropna().unique()),
        contract_types=sorted(df["contract_type"].dropna().unique()),
    )
